#!/usr/bin/env python3
"""2D loss landscapes + gradient field + optimization trajectories — the modern analogue of
``good_notebooks/grad_loss_and_opt_in_2D.ipynb`` (commit c603ed1) on the CURRENT pipeline.

Same figure design, rebuilt on today's stack:
  * loss      : ReconModel charge-Poisson + first-arrival time NLL, averaged over the GN nkeys
                (the ACTUAL reconstruction loss — not the legacy combined-product loss);
  * gradients : reverse-mode AD of that loss (what the Fisher-GN steps on), projected onto
                each scan plane through the physical-parameter map;
  * optimizer : the current fit_track recipe (per the config's gn block + library defaults,
                e.g. AD Fisher, lr annealing, Polyak readout), full trajectory via hist=True;
  * event     : one event generated by TrackingPipeline (config-driven truth treatment);
  * guesses   : THREE Gaussian-perturbed starts around truth, exactly the notebook's logic
                (sigmas 1 m / 3 ns / 10 deg / 100 MeV; seeds 42+i; same clipping).

Physical parameter order mirrors the notebook: [X, Y, Z, t0, theta, phi, E].
Scan pairs and half-ranges (centered on truth) as in the notebook:
  (X,Z) +-2 m | (Y,phi) | (phi,E) +-0.5 rad/+-100 MeV | (X,t0) +-4 ns | (t0,phi) | (t0,E)

    python analysis/paper/fig_loss_landscape.py --config <cfg.json> --output OUT
        [--event 1] [--n-scan 21] [--n-guesses 3]
    # plotting-only from the cached h5 (no recompute):
    python analysis/paper/fig_loss_landscape.py --replot OUT/loss_landscape_2d_ev1.h5 [--vmin 30]
"""
import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from analysis.paper.utils.pipeline import TrackingPipeline, load_config, vec9_to_phys  # noqa: E402

# notebook conventions ---------------------------------------------------------------------
PHYS_NAMES = ['X', 'Y', 'Z', 't0', 'theta', 'phi', 'E']
HALF_RANGE = {0: 2.0, 1: 2.0, 2: 2.0, 3: 4.0, 4: 0.5, 5: 0.5, 6: 250.0}
SCAN_PAIRS = [(0, 2), (1, 5), (5, 6), (0, 3), (3, 5), (3, 6)]
GUESS_SIGMA = dict(position=1.0, t0=3.0, angle=np.radians(10.0), energy=100.0)
GUESS_SEED0 = 42


def phys_from_vec9(v):
    """vec9 -> notebook order [X, Y, Z, t0, theta, phi, E]."""
    x, y, z, phi, theta, t0, E = vec9_to_phys(v)
    return np.array([x, y, z, t0, theta, phi, E])


def notebook_guess(true_phys, bounds, seed):
    """The notebook's generate_initial_guess_from_true, verbatim logic."""
    rng = np.random.default_rng(seed)
    X, Y, Z, t0, th, ph, E = np.array(true_phys, float)
    g = np.array([X + rng.normal(0, GUESS_SIGMA['position']),
                  Y + rng.normal(0, GUESS_SIGMA['position']),
                  Z + rng.normal(0, GUESS_SIGMA['position']),
                  t0 + rng.normal(0, GUESS_SIGMA['t0']),
                  th + rng.normal(0, GUESS_SIGMA['angle']),
                  np.mod(ph + rng.normal(0, GUESS_SIGMA['angle']), 2 * np.pi),
                  np.clip(E + rng.normal(0, GUESS_SIGMA['energy']), 300.0, 2000.0)])
    g[4] = np.clip(g[4], 0, np.pi)
    g[3] = np.clip(g[3], -20.0, 20.0)
    if bounds.get('type') == 'cylinder':
        g[0] = np.clip(g[0], -bounds['r'] * .95, bounds['r'] * .95)
        g[1] = np.clip(g[1], -bounds['r'] * .95, bounds['r'] * .95)
        g[2] = np.clip(g[2], -bounds['H'] / 2 * .95, bounds['H'] / 2 * .95)
    return g


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--config', required=True)
    ap.add_argument('--output', required=True)
    ap.add_argument('--event', type=int, default=1)
    ap.add_argument('--n-scan', type=int, default=21)
    ap.add_argument('--n-guesses', type=int, default=3)
    args = ap.parse_args()

    import jax
    import jax.numpy as jnp
    import h5py
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    from lucid.fitting import fit_track

    cfg = load_config(args.config)
    out_dir = Path(args.output); out_dir.mkdir(parents=True, exist_ok=True)
    NS = args.n_scan

    # ---- event + truth + observables via the CURRENT pipeline (no seeder needed) ----------
    cfg_ev = dict(cfg); cfg_ev['fix_geometry'] = True         # _prepare_event: data only
    pipe = TrackingPipeline(cfg_ev)
    P = pipe._prepare_event(args.event)
    oc = jnp.asarray(P['oc']); ot = jnp.asarray(P['ot'])
    th9 = P['th9']
    true_phys = phys_from_vec9(th9)
    gn = cfg['gn']
    keys = [jax.random.PRNGKey(gn.get('seed', 0) + s) for s in range(gn['nkeys'])]
    print(f"event {args.event}: truth phys [X,Y,Z,t0,th,phi,E] = {np.round(true_phys, 3)}",
          flush=True)

    # ---- the actual reconstruction loss, as a function of the PHYSICAL params -------------
    def t9_of_phys(p):
        return jnp.array([p[6], p[0], p[1], p[2],
                          jnp.sin(p[4]), jnp.cos(p[4]), jnp.sin(p[5]), jnp.cos(p[5]), p[3]])

    def loss_phys(p, key):
        return pipe.model._loss(t9_of_phys(p), oc, ot, key)

    vg = jax.jit(jax.value_and_grad(loss_phys))

    def loss_and_grad(p):
        ls, gs = 0.0, np.zeros(7)
        for k in keys:
            l, g = vg(jnp.asarray(p), k)
            ls += float(l); gs += np.asarray(g)
        return ls / len(keys), gs / len(keys)

    # ---- 2D scans (notebook grid: NS x NS centered on truth) ------------------------------
    scans = []
    for (i1, i2) in SCAN_PAIRS:
        t0s = time.time()
        v1 = np.linspace(true_phys[i1] - HALF_RANGE[i1], true_phys[i1] + HALF_RANGE[i1], NS)
        v2 = np.linspace(true_phys[i2] - HALF_RANGE[i2], true_phys[i2] + HALF_RANGE[i2], NS)
        L = np.zeros((NS, NS)); G = np.zeros((NS, NS, 2))
        for a, p1 in enumerate(v1):
            for b, p2 in enumerate(v2):
                p = true_phys.copy(); p[i1] = p1; p[i2] = p2
                l, g = loss_and_grad(p)
                L[a, b] = l; G[a, b] = (g[i1], g[i2])
        scans.append(dict(i1=i1, i2=i2, v1=v1, v2=v2, L=L, G=G))
        print(f"scan ({PHYS_NAMES[i1]},{PHYS_NAMES[i2]}): {time.time()-t0s:.0f}s", flush=True)

    # Cache the (expensive) scans IMMEDIATELY, before the optimizer fits, so a fit-time
    # failure (e.g. GPU OOM) never discards the ~30 min of loss scans.
    h5path = out_dir / f'loss_landscape_2d_ev{args.event}.h5'
    with h5py.File(h5path, 'w') as h5:
        h5.attrs['config_json'] = json.dumps(cfg); h5.attrs['event'] = args.event
        h5.attrs['phys_order'] = ','.join(PHYS_NAMES)
        h5.create_dataset('truth_phys', data=true_phys)
        for si, sc in enumerate(scans):
            g = h5.create_group(f'scan{si}_{PHYS_NAMES[sc["i1"]]}_{PHYS_NAMES[sc["i2"]]}')
            for k in ('v1', 'v2', 'L', 'G'):
                g.create_dataset(k, data=sc[k])
    print(f"cached scans -> {h5path}", flush=True)

    # ---- 3 optimizations from notebook-style Gaussian guesses -----------------------------
    trajs = []
    for gi in range(args.n_guesses):
        gp = notebook_guess(true_phys, pipe.bounds, GUESS_SEED0 + gi)
        t9g = np.asarray(t9_of_phys(gp))
        res, H = fit_track(pipe.model, oc, ot, t9g, nkeys=gn['nkeys'], niters=gn['niters'],
                           lr=gn['lr'], fisher_mode=gn['fisher_mode'], hist=True)
        tr_phys = np.stack([phys_from_vec9(v) for v in H['traj']])
        fit_phys = phys_from_vec9(res)
        trajs.append(dict(guess=gp, traj=tr_phys, fit=fit_phys))
        print(f"guess {gi}: start {np.round(gp,2)} -> fit {np.round(fit_phys,2)}", flush=True)

    with h5py.File(h5path, 'a') as h5:                    # append trajectories to the cached scans
        h5.attrs['finished'] = datetime.now().isoformat()
        for gi, t in enumerate(trajs):
            g = h5.create_group(f'traj{gi}')
            g.create_dataset('guess', data=t['guess'])
            g.create_dataset('traj', data=t['traj'])
            g.create_dataset('fit', data=t['fit'])
    print(f"cached trajectories -> {h5path}", flush=True)
    replot(str(h5path))
    return 0


# ------------------------------------------------------------------ plotting (notebook style)

def replot(h5_path, vmin=30.0, tag='', contour=False, n_levels=24, zoom_fac=6):
    """Re-make the figure from a cached h5 — EXACT aesthetics of the original notebook's
    LogNorm variant (grad_loss_and_opt_in_2D.ipynb cell 11, invoked as in cell 12:
    trajectory colors from 'Oranges', vmin=1e-1, vmax=95th pct of pooled dLoss)."""
    import h5py
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    import matplotlib.patheffects as pe

    plt.rcParams['text.usetex'] = False
    plt.rcParams['font.family'] = 'serif'
    plt.rcParams['font.size'] = 12

    # notebook gradient pre-normalization scaling (cell 11)
    GSCALE = {'X': .05, 'Y': .05, 'Z': .05, 'theta': .005, 'phi': .005, 't0': .1}

    def format_label(name):
        if name == 'theta': return '$\\theta$ (rad)'
        if name == 'phi': return '$\\phi$ (rad)'
        if name == 't0': return '$t_0$ (ns)'
        if name == 'E': return 'E (MeV)'
        return f'{name} (m)'

    scans, trajs = [], []
    with h5py.File(h5_path, 'r') as f:
        for k in sorted(f.keys()):
            if k.startswith('scan'):
                _, n1, n2 = k.split('_', 2)
                g = f[k]
                scans.append(dict(n1=n1, n2=n2, v1=g['v1'][:], v2=g['v2'][:],
                                  L=g['L'][:], G=g['G'][:]))
            elif k.startswith('traj'):
                trajs.append(dict(guess=f[k]['guess'][:], traj=f[k]['traj'][:],
                                  fit=f[k]['fit'][:]))
        truth = f['truth_phys'][:]
        names = f.attrs['phys_order'].split(',')
    idx = {n: i for i, n in enumerate(names)}

    # cell-12 color scale: pooled dLoss, vmin 1e-1, vmax = 95th percentile
    all_l = np.concatenate([s['L'].flatten() for s in scans])
    all_l = all_l - all_l.min() + 1e-6
    vmax = float(np.percentile(all_l, 95))

    cmap = plt.get_cmap('Oranges')
    n_ev = len(trajs)
    colors = [cmap(0.5 + 0.45 * (i / max(n_ev - 1, 1))) for i in range(n_ev)]   # stronger orange

    fig, axes = plt.subplots(2, 3, figsize=(12, 6))
    axes = axes.flatten()
    axes[2], axes[4] = axes[4], axes[2]          # the notebook's panel swap

    img_handles = []
    for scan, ax in zip(scans, axes):
        n1, n2 = scan['n1'], scan['n2']
        losses = scan['L'].copy()
        losses -= losses.min(); losses += 1e-6
        gradients = scan['G'].copy()
        gradients[:, :, 0] *= GSCALE.get(n1, 1.0)
        gradients[:, :, 1] *= GSCALE.get(n2, 1.0)
        if n2 == 'E':
            gradients[:, :, 1] *= 1000
        if n1 == 'E':
            gradients[:, :, 0] *= 1000

        p1, p2 = scan['v1'], scan['v2']
        U = -gradients[:, :, 0].T; V = -gradients[:, :, 1].T
        nrm = np.sqrt(U**2 + V**2); nrm = np.where(nrm == 0, 1, nrm)
        U /= nrm; V /= nrm

        if contour:
            # smooth filled contours: cubic-interpolate the coarse NSxNS grid to a fine mesh,
            # then draw log-spaced filled levels + light contour lines for the loss "topography".
            from scipy.ndimage import zoom
            Z = np.clip(zoom(losses.T, zoom_fac, order=3), vmin, None)
            xf = np.linspace(p1[0], p1[-1], Z.shape[1])
            yf = np.linspace(p2[0], p2[-1], Z.shape[0])
            levels = np.logspace(np.log10(vmin), np.log10(vmax), n_levels)
            im = ax.contourf(xf, yf, Z, levels=levels, cmap='viridis',
                             norm=LogNorm(vmin=vmin, vmax=vmax), extend='both')
            ax.contour(xf, yf, Z, levels=levels[::3], colors='white',
                       linewidths=0.4, alpha=0.45, norm=LogNorm(vmin=vmin, vmax=vmax))
            ax.set_aspect('auto')
        else:
            im = ax.imshow(losses.T, extent=[p1[0], p1[-1], p2[0], p2[-1]],
                           origin='lower', aspect='auto', cmap='viridis',
                           norm=LogNorm(vmin=vmin, vmax=vmax))
        img_handles.append(im)
        ax.streamplot(np.linspace(p1[0], p1[-1], len(p1)), np.linspace(p2[0], p2[-1], len(p2)),
                      U, V, color='white', density=0.6, linewidth=0.9, arrowsize=1.0)
        for t, color in zip(trajs, colors):
            xp, yp = t['traj'][:, idx[n1]], t['traj'][:, idx[n2]]
            ax.plot(xp, yp, color=color, linewidth=3.6, zorder=90, solid_capstyle='round',
                    path_effects=[pe.Stroke(linewidth=5.4, foreground='black', alpha=0.55),
                                  pe.Normal()])
            ax.scatter(xp, yp, color=color, s=24, zorder=91, edgecolors='black', linewidths=0.3)
            ax.plot(t['fit'][idx[n1]], t['fit'][idx[n2]], color='cyan', marker='x',
                    markersize=16, markeredgewidth=3.2, zorder=100)
        ax.plot(truth[idx[n1]], truth[idx[n2]], color='deeppink', marker='*',
                markersize=20, zorder=99)
        ax.set_xlabel(format_label(n1)); ax.set_ylabel(format_label(n2))
        ax.set_xlim(p1[0], p1[-1]); ax.set_ylim(p2[0], p2[-1])

    cbar_ax = fig.add_axes([0.92, 0.15, 0.015, 0.7])
    cbar = fig.colorbar(img_handles[0], cax=cbar_ax)
    cbar.set_ticks([])                                    # no numeric ticks — just the label
    cbar.set_label('$\\Delta$ Loss (log scale)', fontsize=12)
    legend_elements = [
        plt.Line2D([], [], color=colors[-1], lw=2, label='Optimization paths'),
        plt.Line2D([], [], color='cyan', marker='x', lw=0, markersize=10, label='Reconstructed'),
        plt.Line2D([], [], color='deeppink', marker='*', lw=0, markersize=12, label='True')]
    fig.legend(handles=legend_elements, loc='upper center', ncol=3, frameon=False, fontsize=13)
    plt.subplots_adjust(left=0.05, right=0.90, top=0.92, bottom=0.08, wspace=0.34, hspace=0.32)

    base = str(Path(h5_path).with_suffix('')) + tag
    for ext in ('png', 'pdf'):
        fig.savefig(f'{base}.{ext}', dpi=150, bbox_inches='tight')
    print(f"wrote {base}.png (+pdf)", flush=True)


if __name__ == '__main__':
    if '--replot' in sys.argv:
        _vm = float(sys.argv[sys.argv.index('--vmin') + 1]) if '--vmin' in sys.argv else 30.0
        _contour = '--contour' in sys.argv
        _nl = int(sys.argv[sys.argv.index('--nlevels') + 1]) if '--nlevels' in sys.argv else 24
        _tag = ('_contour' if _contour else '') + (f'_nl{_nl}' if '--nlevels' in sys.argv else '') \
            + (f'_vmin{_vm:g}' if '--vmin' in sys.argv else '')
        replot(sys.argv[sys.argv.index('--replot') + 1], vmin=_vm, tag=_tag, contour=_contour,
               n_levels=_nl)
        sys.exit(0)
    sys.exit(main())
