"""The hierarchical grid seeder: does it find the vertex, and does it do it without knowing it.

`lucid.optimization.grid_search` supplies the starting point for every reconstruction that goes
through `TrackingPipeline`. Its signature takes the truth as an argument
(`true_position`, `true_t0`), used only to report `position_error`, `t0_error` and
`distance_to_true`. If truth ever leaked into the scoring, the seeder would become an oracle and
no downstream test would notice, so the first tests check that an absurd truth changes nothing
the search returns.

The rest is a closure on noiseless arrival times generated by the model `grid_origin_time_loss`
inverts (straight-line flight at the water group velocity), with tolerances set at what the
search actually reaches. `detector_bounds` is the plain dict `get_detector_bounds` returns, so no
detector or simulator is needed.
"""
import numpy as np
import pytest

from lucid.optimization.grid_search import (
    hierarchical_position_grid_search, hierarchical_position_grid_search_3d,
    is_point_inside_detector, evaluate_loss_batch,
)

C_MEDIUM = 0.299792 / 1.33          # m/ns, as grid_origin_time_loss assumes
PMT_R = 0.25                        # the photosensor radius it subtracts
BOUNDS = {'type': 'cylinder', 'r': 8.0, 'H': 16.0}
TRUE_POS = np.array([2.1, -1.4, 3.0])
TRUE_T0 = 4.0


def _sensors(n_phi=16, n_z=7):
    """PMTs on the barrel of the cylinder — enough angular spread to triangulate."""
    phi = np.linspace(0, 2 * np.pi, n_phi, endpoint=False)
    z = np.linspace(-7.0, 7.0, n_z)
    p, zz = np.meshgrid(phi, z, indexing='ij')
    return np.stack([BOUNDS['r'] * np.cos(p).ravel(),
                     BOUNDS['r'] * np.sin(p).ravel(),
                     zz.ravel()], axis=1)


def _arrivals(pos, t0, sensors):
    """Noiseless direct light: t = t0 + (d - r_pmt)/c, the model the loss inverts."""
    d = np.linalg.norm(sensors - np.asarray(pos)[None, :], axis=1)
    return t0 + (d - PMT_R) / C_MEDIUM


SENSORS = _sensors()
TIMES = _arrivals(TRUE_POS, TRUE_T0, SENSORS)
CHARGE = np.ones(len(SENSORS))       # all sensors lit; the loss masks on charge > 0

SEARCH = dict(detector_bounds=BOUNDS, n_div=5, t0_n_div=7, levels=4,
              fraction=0.9, t0_min=-2.0, t0_max=10.0, min_L=0.02, verbosity=0)


def _run(true_position, true_t0, **over):
    kw = {**SEARCH, **over}
    return hierarchical_position_grid_search(SENSORS, TIMES, CHARGE,
                                             true_position, true_t0, 0.0, **kw)


# --------------------------------------------------------------------------------------------
# The one that matters: truth is reported, never used.
# --------------------------------------------------------------------------------------------

def test_the_seed_does_not_depend_on_the_truth_it_is_handed():
    """A seeder that reads its own answer key is an oracle, and nothing downstream could tell.

    Everything the search RETURNS as an answer must be bit-identical when the truth argument is
    replaced by nonsense. Only the reported error fields may move.
    """
    honest = _run(TRUE_POS, TRUE_T0)
    lied_to = _run(np.array([-7.5, 7.5, -7.5]), -99.0)

    np.testing.assert_array_equal(honest['best_position'], lied_to['best_position'])
    assert honest['best_t0'] == lied_to['best_t0']
    assert honest['best_loss'] == lied_to['best_loss']
    assert honest['n_t0_tested'] == lied_to['n_t0_tested']
    # and the error fields, which are the only thing truth may touch, DID move — otherwise this
    # test would also pass against a search that ignored its inputs entirely
    assert honest['position_error'] != lied_to['position_error']
    assert honest['t0_error'] != lied_to['t0_error']


def test_the_3d_search_is_also_truth_independent():
    """The 3D search is where the refinement loop lives, so it is checked separately."""
    kw = dict(detector_bounds=BOUNDS, n_div=5, levels=4, fraction=0.9, min_L=0.02, verbosity=0)
    a = hierarchical_position_grid_search_3d(SENSORS, TIMES, CHARGE, TRUE_POS, TRUE_T0, **kw)
    b = hierarchical_position_grid_search_3d(SENSORS, TIMES, CHARGE,
                                             np.array([-7.5, 7.5, -7.5]), TRUE_T0, **kw)
    np.testing.assert_array_equal(a['best_position'], b['best_position'])
    assert a['best_loss'] == b['best_loss']


# --------------------------------------------------------------------------------------------
# Does it work.
# --------------------------------------------------------------------------------------------

T0_STEP = (SEARCH['t0_max'] - SEARCH['t0_min']) / (SEARCH['t0_n_div'] - 1)     # 2.0 ns


def _degeneracy_bound(res):
    """How far the vertex may legitimately sit, given where t0 landed.

    Vertex and t0 are degenerate along the line of sight: sliding t0 by dt and the vertex by
    c*dt leaves the arrival pattern almost unchanged. `t0` is searched on a coarse grid, so
    whenever it lands a step off, the position follows by that much and the seed is still the
    right answer to the question actually posed. The 0.10 m slack covers the on-grid accuracy
    (under 7 cm when t0 lands exactly).

    It is the same degeneracy `lucid.fitting.recon.ProjectedReconProblem` projects out of the
    time term downstream.
    """
    return C_MEDIUM * abs(res['best_t0'] - TRUE_T0) + 0.10


def test_it_recovers_a_synthetic_vertex():
    """Noiseless data generated by the model the loss inverts, so the answer is known."""
    res = _run(TRUE_POS, TRUE_T0)
    err = float(np.linalg.norm(res['best_position'] - TRUE_POS))
    assert abs(res['best_t0'] - TRUE_T0) < 1e-9, 'this vertex should land exactly on the t0 grid'
    assert err < 0.10, f'seed is {err:.3f} m from the vertex it was given the data of'


def test_it_recovers_t0_to_within_its_grid_step():
    res = _run(TRUE_POS, TRUE_T0)
    assert abs(res['best_t0'] - TRUE_T0) <= T0_STEP, (
        f"t0 seed {res['best_t0']:.2f} vs truth {TRUE_T0}; the grid step is {T0_STEP:.2f} ns")


def test_a_displaced_vertex_moves_the_seed():
    """The seed must track the data, not land in the same place regardless.

    The tolerance is the vertex-t0 degeneracy bound rather than a flat number: this vertex is the
    one whose t0 lands a grid step off, and demanding better than the degeneracy allows would be
    demanding the seeder resolve something the data does not.
    """
    other = np.array([-3.0, 2.5, -4.0])
    res = hierarchical_position_grid_search(
        SENSORS, _arrivals(other, TRUE_T0, SENSORS), CHARGE, TRUE_POS, TRUE_T0, 0.0, **SEARCH)
    err = float(np.linalg.norm(res['best_position'] - other))
    assert err < _degeneracy_bound(res), (
        f'seed {err:.3f} m off, beyond the {_degeneracy_bound(res):.3f} m the '
        f"{abs(res['best_t0'] - TRUE_T0):.1f} ns t0 offset can explain")
    assert float(np.linalg.norm(res['best_position'] - TRUE_POS)) > 1.0


def test_the_seed_stays_inside_the_fiducial_fraction():
    res = _run(TRUE_POS, TRUE_T0, fraction=0.5)
    assert is_point_inside_detector(tuple(res['best_position']), BOUNDS, fraction=0.5)


# --------------------------------------------------------------------------------------------
# The loss property the seeder's robustness rests on.
# --------------------------------------------------------------------------------------------

@pytest.mark.parametrize('delta', [0.5, 1.0, 2.0])
def test_early_light_is_penalised_far_more_heavily_than_late(delta):
    """Scattered and reflected photons arrive LATE, never early.

    A symmetric residual lets that one-sided tail drag the seed metres off, so a hypothesis
    implying photons arrived EARLIER than straight-line flight allows must cost far more than one
    implying they arrived late.

    Posed through t0 at the TRUE position, because that isolates the sign cleanly: with
    ``r = t_obs - t_pred - t0``, raising t0 drives every residual negative (early-looking) and
    lowering it drives them positive (late-looking). Displacing the vertex instead moves it
    closer to some sensors and further from others, which mixes the two.
    """
    late = float(evaluate_loss_batch(TRUE_POS[None, :], SENSORS, TIMES, CHARGE,
                                     TRUE_T0 - delta)[0])
    early = float(evaluate_loss_batch(TRUE_POS[None, :], SENSORS, TIMES, CHARGE,
                                      TRUE_T0 + delta)[0])
    assert early > late + 10.0, (
        f'at {delta} ns: early-looking costs {early:.3f}, late-looking {late:.3f} — the '
        f'one-sided penalty that makes this robust to scattered light is not in effect')


def test_the_loss_is_minimised_at_the_truth_among_a_scan():
    """A crude global check: over a coarse scan the true vertex wins."""
    rng = np.random.default_rng(0)
    cand = np.concatenate([TRUE_POS[None, :], rng.uniform(-6, 6, (60, 3))], axis=0)
    losses = np.asarray(evaluate_loss_batch(cand, SENSORS, TIMES, CHARGE, TRUE_T0))
    assert int(np.argmin(losses)) == 0, 'a random point beat the true vertex'


@pytest.mark.parametrize('point,inside', [
    ((0.0, 0.0, 0.0), True), ((7.9, 0.0, 0.0), True), ((8.1, 0.0, 0.0), False),
    ((0.0, 0.0, 7.9), True), ((0.0, 0.0, 8.1), False),
])
def test_bounds_check_matches_the_cylinder(point, inside):
    assert bool(is_point_inside_detector(point, BOUNDS, fraction=1.0)) is inside
