"""Cached production lookup for smooth SK 20-inch PMT coverage."""

from pathlib import Path
from typing import NamedTuple

import jax
import jax.numpy as jnp
import numpy as np

from lucid.utils import base_dir_path

from .sk_pmt import BARREL_INACTIVE_BAND_Z, GEANT_PMT_RADIUS
from .sk_pmt_jax import intersect_sk20inch_pmt_jax


_LOOKUP_VERSION = 1


class SKPMTCoverageLookup(NamedTuple):
    """Regular-grid coverage table for differentiable trilinear lookup."""

    incidence_cosine: jnp.ndarray
    offset_parallel: jnp.ndarray
    offset_perpendicular: jnp.ndarray
    cap_coverage: jnp.ndarray
    barrel_coverage: jnp.ndarray
    sigma: float


def _cache_path(cache_dir, sigma, n_incidence, grid_spacing, tail_sigma,
                raster_oversample):
    directory = Path(
        cache_dir
        if cache_dir is not None
        else Path(base_dir_path()) / "spatial_overlap_integrals"
    )
    directory.mkdir(parents=True, exist_ok=True)
    name = (
        f"sk20inch_v{_LOOKUP_VERSION}_sigma{sigma:.7f}"
        f"_nmu{n_incidence}_dx{grid_spacing:.7f}"
        f"_tail{tail_sigma:.2f}_os{raster_oversample}.npz"
    )
    return directory / name


def _from_arrays(mu, parallel, perpendicular, cap, barrel, sigma):
    return SKPMTCoverageLookup(
        incidence_cosine=jnp.asarray(mu),
        offset_parallel=jnp.asarray(parallel),
        offset_perpendicular=jnp.asarray(perpendicular),
        cap_coverage=jnp.asarray(cap),
        barrel_coverage=jnp.asarray(barrel),
        sigma=float(sigma),
    )


def build_sk20inch_coverage_lookup(
    sigma,
    *,
    n_incidence=31,
    grid_spacing=None,
    tail_sigma=5.0,
    raster_oversample=4,
    cache=True,
    cache_dir=None,
):
    """Build or load a smooth coverage lookup for one Gaussian width.

    The table axes are incidence cosine, signed offset parallel to the PMT
    axis projected into the ray plane, and the absolute perpendicular offset.
    It is generated by Gaussian-filtering hard SK silhouettes. Step 4 verifies
    that this convolution agrees with the curved-surface integral.
    """
    sigma = float(sigma)
    if not np.isfinite(sigma) or sigma <= 0.0:
        raise ValueError("sigma must be finite and positive")
    if int(n_incidence) != n_incidence or n_incidence < 2:
        raise ValueError("n_incidence must be an integer of at least 2")
    n_incidence = int(n_incidence)
    if not np.isfinite(tail_sigma) or tail_sigma < 3.0:
        raise ValueError("tail_sigma must be finite and at least 3")
    if (int(raster_oversample) != raster_oversample
            or raster_oversample < 1):
        raise ValueError("raster_oversample must be a positive integer")
    raster_oversample = int(raster_oversample)

    if grid_spacing is None:
        grid_spacing = max(sigma / 4.0, 0.002)
    grid_spacing = float(grid_spacing)
    if not np.isfinite(grid_spacing) or grid_spacing <= 0.0:
        raise ValueError("grid_spacing must be finite and positive")

    extent = GEANT_PMT_RADIUS + tail_sigma * sigma
    half_intervals = max(2, int(np.ceil(extent / grid_spacing)))
    # Adjust the spacing slightly so zero and both endpoints are grid nodes.
    grid_spacing = extent / half_intervals
    coordinate = np.arange(-half_intervals, half_intervals + 1) * grid_spacing
    midpoint = half_intervals
    mu_values = np.linspace(0.0, 1.0, n_incidence)

    path = _cache_path(
        cache_dir, sigma, n_incidence, grid_spacing, tail_sigma,
        raster_oversample)
    if cache and path.exists():
        with np.load(path) as saved:
            if int(saved["version"]) == _LOOKUP_VERSION:
                return _from_arrays(
                    saved["incidence_cosine"],
                    saved["offset_parallel"],
                    saved["offset_perpendicular"],
                    saved["cap_coverage"],
                    saved["barrel_coverage"],
                    float(saved["sigma"]),
                )

    fine_half_intervals = half_intervals * raster_oversample
    fine_grid_spacing = grid_spacing / raster_oversample
    fine_coordinate = (
        np.arange(-fine_half_intervals, fine_half_intervals + 1)
        * fine_grid_spacing
    )
    first_coordinate, second_coordinate = np.meshgrid(
        fine_coordinate, fine_coordinate, indexing="ij")
    flat_first = first_coordinate.reshape(-1)
    flat_second = second_coordinate.reshape(-1)

    @jax.jit
    def raster_intersections(origins, direction):
        return jax.vmap(
            lambda origin: intersect_sk20inch_pmt_jax(
                origin,
                direction,
                jnp.zeros(3),
                jnp.array([0.0, 0.0, 1.0]),
                barrel=False,
            )
        )(origins)

    from scipy.ndimage import gaussian_filter

    cap_tables = []
    barrel_tables = []
    gaussian_sigma_pixels = sigma / fine_grid_spacing
    for mu in mu_values:
        transverse = np.sqrt(max(0.0, 1.0 - mu * mu))
        direction = np.array([transverse, 0.0, -mu])
        parallel_basis = np.array([mu, 0.0, transverse])
        perpendicular_basis = np.array([0.0, -1.0, 0.0])
        origins = (
            -direction[None, :]
            + flat_first[:, None] * parallel_basis[None, :]
            + flat_second[:, None] * perpendicular_basis[None, :]
        )
        hits = raster_intersections(
            jnp.asarray(origins), jnp.asarray(direction))
        fine_size = fine_coordinate.size
        intersects = np.asarray(hits.intersects).reshape(fine_size, fine_size)
        axial = np.asarray(hits.axial_position).reshape(fine_size, fine_size)
        cap_mask = intersects.astype(float)
        barrel_mask = (
            intersects & (axial > BARREL_INACTIVE_BAND_Z)).astype(float)
        cap_smoothed = gaussian_filter(
            cap_mask,
            gaussian_sigma_pixels,
            mode="constant",
            cval=0.0,
            truncate=tail_sigma,
        )
        barrel_smoothed = gaussian_filter(
            barrel_mask,
            gaussian_sigma_pixels,
            mode="constant",
            cval=0.0,
            truncate=tail_sigma,
        )
        # Downsample to the runtime table grid after antialiasing the hard
        # silhouette. Reflection symmetry makes the second offset non-negative.
        cap_coarse = cap_smoothed[::raster_oversample,
                                  ::raster_oversample]
        barrel_coarse = barrel_smoothed[::raster_oversample,
                                        ::raster_oversample]
        cap_tables.append(cap_coarse[:, midpoint:])
        barrel_tables.append(barrel_coarse[:, midpoint:])

    cap_tables = np.asarray(cap_tables, dtype=np.float32)
    barrel_tables = np.asarray(barrel_tables, dtype=np.float32)
    perpendicular = coordinate[midpoint:]

    if cache:
        np.savez_compressed(
            path,
            version=np.asarray(_LOOKUP_VERSION),
            sigma=np.asarray(sigma),
            incidence_cosine=mu_values,
            offset_parallel=coordinate,
            offset_perpendicular=perpendicular,
            cap_coverage=cap_tables,
            barrel_coverage=barrel_tables,
        )

    return _from_arrays(
        mu_values, coordinate, perpendicular,
        cap_tables, barrel_tables, sigma)


def _normalize(vector):
    return vector / jnp.linalg.norm(vector)


def _transverse_basis(axis):
    sign = jnp.copysign(1.0, axis[2])
    factor = -1.0 / (sign + axis[2])
    cross_term = axis[0] * axis[1] * factor
    first = jnp.array([
        1.0 + sign * axis[0] * axis[0] * factor,
        sign * cross_term,
        -sign * axis[0],
    ])
    return first


def sk20inch_lookup_coordinates(
    ray_origin,
    ray_direction,
    pmt_position,
    pmt_direction,
):
    """Return lookup coordinates for an arbitrary world-space ray and PMT."""
    origin = jnp.asarray(ray_origin)
    direction = _normalize(jnp.asarray(ray_direction))
    pmt_position = jnp.asarray(pmt_position)
    axis = _normalize(jnp.asarray(pmt_direction))

    incidence_cosine = jnp.clip(-jnp.dot(direction, axis), 0.0, 1.0)
    projected_axis = axis - jnp.dot(axis, direction) * direction
    projected_norm = jnp.sqrt(
        jnp.dot(projected_axis, projected_axis) + 1e-20)
    fallback = _transverse_basis(direction)
    parallel_basis = jnp.where(
        projected_norm > 1e-8,
        projected_axis / projected_norm,
        fallback,
    )
    perpendicular_basis = jnp.cross(direction, parallel_basis)
    perpendicular_basis = _normalize(perpendicular_basis)

    to_pmt = pmt_position - origin
    closest_point = origin + jnp.dot(to_pmt, direction) * direction
    line_offset = closest_point - pmt_position
    parallel_offset = jnp.dot(line_offset, parallel_basis)
    perpendicular_offset = jnp.abs(
        jnp.dot(line_offset, perpendicular_basis))
    return incidence_cosine, parallel_offset, perpendicular_offset


def _grid_coordinate(value, grid):
    step = grid[1] - grid[0]
    coordinate = (value - grid[0]) / step
    valid = (coordinate >= 0.0) & (coordinate <= grid.shape[0] - 1)
    clipped = jnp.clip(coordinate, 0.0, grid.shape[0] - 1)
    lower = jnp.minimum(jnp.floor(clipped).astype(jnp.int32),
                        grid.shape[0] - 2)
    fraction = clipped - lower
    return lower, fraction, valid


def sk20inch_lookup_coverage(
    ray_origin,
    ray_direction,
    pmt_position,
    pmt_direction,
    barrel,
    lookup,
):
    """Evaluate the cached coverage table with trilinear interpolation."""
    mu, parallel, perpendicular = sk20inch_lookup_coordinates(
        ray_origin, ray_direction, pmt_position, pmt_direction)
    i_mu, f_mu, valid_mu = _grid_coordinate(
        mu, lookup.incidence_cosine)
    i_parallel, f_parallel, valid_parallel = _grid_coordinate(
        parallel, lookup.offset_parallel)
    i_perpendicular, f_perpendicular, valid_perpendicular = _grid_coordinate(
        perpendicular, lookup.offset_perpendicular)
    table = jnp.where(
        jnp.asarray(barrel), lookup.barrel_coverage, lookup.cap_coverage)

    value = 0.0
    for delta_mu in (0, 1):
        weight_mu = f_mu if delta_mu else 1.0 - f_mu
        for delta_parallel in (0, 1):
            weight_parallel = (
                f_parallel if delta_parallel else 1.0 - f_parallel)
            for delta_perpendicular in (0, 1):
                weight_perpendicular = (
                    f_perpendicular if delta_perpendicular
                    else 1.0 - f_perpendicular)
                value = value + (
                    weight_mu * weight_parallel * weight_perpendicular
                    * table[
                        i_mu + delta_mu,
                        i_parallel + delta_parallel,
                        i_perpendicular + delta_perpendicular,
                    ]
                )

    valid = valid_mu & valid_parallel & valid_perpendicular
    return jnp.where(valid, value, 0.0)


__all__ = [
    "SKPMTCoverageLookup",
    "build_sk20inch_coverage_lookup",
    "sk20inch_lookup_coordinates",
    "sk20inch_lookup_coverage",
]
