"""hello_reconstruct — track/shower reconstruction via lucid.fitting, muon or electron.

A 9-parameter [E, x, y, z, dir, t0] Fisher-Gauss-Newton fit, on a Poisson-charge +
first-arrival order-statistic time loss (lucid.fitting). One script, two study axes via CLI:

  --closure    (default) prediction-vs-prediction: the "data" event is generated by the
               SIREN emitter for --data, and fitted with the SIREN model for --hypothesis.
               With --data == --hypothesis this is self-consistent (no model mismatch).
  --data-fit   prediction-vs-data: the "data" event is a real GEANT4 event (PhotonSim ROOT
               for --data, randomized into the fiducial volume so truth is exact), fitted
               with the SIREN model for --hypothesis. Adds the GEANT4-vs-SIREN mismatch floor.

  --data {mu,e}        particle that produced the data event   (default mu)
  --hypothesis {mu,e}  particle model used to reconstruct it   (default mu)

Cross-particle runs (e.g. --data e --hypothesis mu) probe how well one particle hypothesis
explains the other's event. SK_like geometry; 1000 MeV. Run inside the container with
PYTHONPATH=dev LUCiD, CWD = the LUCiD checkout; fast on GPU.
"""
import argparse
import jax, jax.numpy as jnp, numpy as np
from lucid.geometry import generate_detector
from lucid.simulation import setup_event_simulator
from lucid.detector_params import load_detector_params
from lucid.fitting import ReconModel, fit_track, vec9_from_track, vec9_dir, track_from_vec9

GEOM, PHYS, K = 'config/SK_like_geom_config.json', 'config/SK_like_physics_config.json', 8
GRID = dict(n_cap=40, n_angular=80, n_height=40)
E0 = 1000.0                                   # truth energy (MeV) for closure / fallback
LONG = {'mu': 'muon', 'e': 'electron'}
# aggressive from-scratch start: fail by up to these amounts, magnitude sampled uniformly
DPOS, DE, DANG, DT0 = 3.0, 200.0, 10.0, 3.0   # metres, MeV, degrees, ns
# PhotonSim Cherenkov emission band (nm) — QE applied over the true band for GEANT4 data
CH_BAND = (274.91, 673.83)


def perturb(th9, rng):
    """Aggressive start = truth + uniform-magnitude offset in each physical quantity."""
    E_t, pos_t, d_t, t0_t = th9[0], th9[1:4], vec9_dir(th9), th9[8]
    dv = rng.normal(size=3); dv /= np.linalg.norm(dv); dv *= rng.uniform(0, DPOS)   # |Δvtx| ≤ 3 m
    ang = np.radians(rng.uniform(0, DANG))                                          # tilt ≤ 10°
    a = rng.normal(size=3); a -= (a @ d_t) * d_t; a /= np.linalg.norm(a)            # ⟂ axis
    d_s = d_t * np.cos(ang) + np.cross(a, d_t) * np.sin(ang)
    return vec9_from_track(float(E_t + rng.uniform(-DE, DE)), (pos_t + dv).tolist(),
                           d_s.tolist(), t0=float(t0_t + rng.uniform(-DT0, DT0)))


def _rotax(u, deg):
    a = np.radians(deg); ca, sa = np.cos(a), np.sin(a); u = u / np.linalg.norm(u)
    ux = np.array([[0, -u[2], u[1]], [u[2], 0, -u[0]], [-u[1], u[0], 0]])
    return np.eye(3) * ca + sa * ux + (1 - ca) * np.outer(u, u)


def rand_tf(raw, ev, fidr, fidz):
    """Randomize a GEANT4 event (gun fires +z from origin) into the fiducial volume;
    return (raw', truth vertex [m], truth dir). Exact truth follows the rigid transform."""
    rng = np.random.default_rng(100003 + ev); beta = np.degrees(np.arccos(rng.uniform(-1, 1)))
    al = rng.uniform(0, 2 * np.pi); axis = np.array([-np.sin(al), np.cos(al), 0.])
    rr = fidr * np.sqrt(rng.uniform()); ph = rng.uniform(0, 2 * np.pi)
    sh = np.array([rr * np.cos(ph), rr * np.sin(ph), rng.uniform(-fidz, fidz)]) * 100.0
    raw = dict(raw); O = np.asarray(raw['photon_origins']).astype(float)
    D = np.asarray(raw['photon_directions']).astype(float); R = _rotax(axis, beta); c = O.mean(0)
    raw['photon_origins'] = (O - c) @ R.T + c + sh
    raw['photon_directions'] = D @ R.T
    vtx_true = ((np.zeros(3) - c) @ R.T + c + sh) / 100.0
    return raw, vtx_true, np.array([0., 0., 1.]) @ R.T


def make_data(mode, data_particle, hyp_particle, ND, dp_data, event):
    """Return (obs_counts, obs_times, truth_vec9). Builds the appropriate data source."""
    if mode == 'closure':
        data_sim = setup_event_simulator(GEOM, 250_000, temperature=None, K=K, use_expected_value=False,
                                         hit_mode='realistic', charge_resolution=None, particle=data_particle,
                                         physics_config=PHYS, default_detector_params=dp_data,
                                         wavelength_mode=True, **GRID)
        th9 = vec9_from_track(E0, position=[1.5, -0.8, 2.0], direction=[0.3, 0.1, 0.95], t0=0.)
        c, t = jax.lax.stop_gradient(data_sim(track_from_vec9(jnp.asarray(th9)), jax.random.PRNGKey(0)))
    else:  # data-fit: real GEANT4 photons for --data
        from lucid.sources.event_io import read_photon_data_from_photonsim, pad_photon_data
        root = f'data/water/{data_particle}/1000MeV_100events.root'
        data_sim = setup_event_simulator(GEOM, 400_000, temperature=None, K=K, is_data=True,
                                         hit_mode='realistic', charge_resolution=None, particle=data_particle,
                                         physics_config=PHYS, default_detector_params=dp_data,
                                         wavelength_mode=True, **GRID)
        raw = read_photon_data_from_photonsim(root, event)
        energy = float(raw['energy']) if 'energy' in raw else E0
        raw, vtx_true, dir_true = rand_tf(raw, event, 12.0, 12.0)
        th9 = vec9_from_track(energy, vtx_true.tolist(), dir_true.tolist(), t0=0.)
        pd, _ = pad_photon_data(raw, 400_000)
        dummy = track_from_vec9(jnp.asarray(vec9_from_track(E0, [0, 0, 0], [0, 0, 1], t0=0.)))
        c, t = jax.lax.stop_gradient(data_sim(dummy, jax.random.PRNGKey(7000 + event), pd))
    oc = jnp.asarray(np.asarray(c)); ot = jnp.asarray(np.where(np.asarray(c) > 0, np.asarray(t), 0.))
    return oc, ot, th9


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument('--closure', action='store_true', help='prediction-vs-prediction (default)')
    g.add_argument('--data-fit', dest='data_fit', action='store_true', help='prediction-vs-GEANT4-data')
    ap.add_argument('--data', choices=['mu', 'e'], default='mu', help='particle of the data event')
    ap.add_argument('--hypothesis', choices=['mu', 'e'], default='mu', help='particle model to fit with')
    ap.add_argument('--event', type=int, default=0, help='ROOT event index (data-fit)')
    ap.add_argument('--seed', type=int, default=1, help='RNG seed for the start offset')
    ap.add_argument('--niters', type=int, default=130)
    args = ap.parse_args()
    mode = 'data-fit' if args.data_fit else 'closure'
    data_p, hyp_p = LONG[args.data], LONG[args.hypothesis]

    det = generate_detector(GEOM); ND = len(det.all_points)
    dp_data = load_detector_params(PHYS, num_sensors=ND)
    dp_data = dp_data._replace(response=dp_data.response._replace(tts=jnp.asarray(2.5)))

    # hypothesis predictor (SOFT, differentiable). Band-consistent only for real GEANT4 data.
    band = CH_BAND if mode == 'data-fit' else None
    pred = setup_event_simulator(GEOM, 250_000, temperature=0.1, K=K, hit_mode='per_photon',
                                 physics_config=PHYS, default_detector_params=True, particle=hyp_p,
                                 wavelength_mode=True, pos_grad_threshold=K, n_grad_iters=K,
                                 cherenkov_emission_band=band, **GRID)
    model = ReconModel(pred, ND, sigma=2.5, delta=1.0)

    oc, ot, th9 = make_data(mode, data_p, hyp_p, ND, dp_data, args.event)
    start = perturb(th9, np.random.default_rng(args.seed))
    res = fit_track(model, oc, ot, start, nkeys=2, niters=args.niters)

    td = vec9_dir(th9)
    sv = np.linalg.norm((start - th9)[1:4]) * 100; sd = np.degrees(np.arccos(np.clip(vec9_dir(start) @ td, -1, 1)))
    fv = np.linalg.norm((res - th9)[1:4]) * 100; fd = np.degrees(np.arccos(np.clip(vec9_dir(res) @ td, -1, 1)))
    tag = f'{mode}  data={args.data}  hypothesis={args.hypothesis}'
    print(f'[{tag}]  truth E {th9[0]:.0f} MeV')
    print(f'  start  vtx {sv:6.1f} cm   E {start[0]-th9[0]:+7.0f} MeV   dir {sd:5.1f}°   t0 {start[8]-th9[8]:+5.2f} ns')
    print(f'  fit    vtx {fv:6.1f} cm   E {res[0]-th9[0]:+7.1f} MeV   dir {fd:5.2f}°   t0 {res[8]-th9[8]:+5.2f} ns')


if __name__ == '__main__':
    main()
